/* WMR200LOG - WMR200 Station Reader v0.1
 * based on driver.c generated by usbsnoop2libusb.pl - (c) timo.lindfors@iki.fi
 */ 

/* Author: Thomas Wood */

#include <stdio.h>
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <signal.h>
#include <ctype.h>
#include <usb.h>
#include <glib.h>

struct usb_dev_handle *devh;

void
release_usb_device (int dummy)
{
  int ret;
  ret = usb_release_interface(devh, 0);
  if (!ret)
    fprintf (stderr, "failed to release interface: %d\n", ret);
  usb_close(devh);
  if (!ret)
    fprintf (stderr, "failed to close interface: %d\n", ret);
  exit(1);
}

struct usb_device *find_device(int vendor, int product) {
    struct usb_bus *bus;
    
    for (bus = usb_get_busses(); bus; bus = bus->next) {
	struct usb_device *dev;
	
	for (dev = bus->devices; dev; dev = dev->next) {
	    if (dev->descriptor.idVendor == vendor
		&& dev->descriptor.idProduct == product)
		return dev;
	}
    }
    return NULL;
}

void print_bytes(char *bytes, int len) {
  int i;

  fprintf (stderr, "DATA: ");
  if (len > 0) {
		for (i=0; i<len; i++) {
		    fprintf(stderr, "%02x ", (int)((unsigned char)bytes[i]));
		}
	}
  fprintf (stderr, "\n");
}

int
main(int argc, char **argv)
{
  int ret, vendor, product;
  struct usb_device *dev;
  char buf[255];
  char buf2[255];
  char data[1024];
  int data_pos;
  int pid;

  fprintf(stderr, "WMR200LOG - Weather Station Reader\n");

  usb_init();
  usb_find_busses();
  usb_find_devices();

  vendor = 0x0fde;
  product = 0xca01; 

  dev = find_device(vendor, product);
  assert(dev);

  devh = usb_open(dev);
  assert(devh);

  signal(SIGTERM, release_usb_device);

  ret = usb_get_driver_np(devh, 0, buf, sizeof(buf));
  if (ret == 0)
  {
    fprintf (stderr, "interface 0 already claimed by driver \"%s\", attempting to detach it\n", buf);
    ret = usb_detach_kernel_driver_np(devh, 0);
    fprintf (stderr, "usb_detach_kernel_driver_np returned %d\n", ret);
  } else if (ret < 0)
    fprintf (stderr, "Get driver failed (ret: %d)\n: %s\n", ret, usb_strerror());

  ret = usb_claim_interface(devh, 0);
  if (ret != 0)
  {
    fprintf (stderr, "claim failed with error %d:\n %s\n", ret, usb_strerror());
    exit(1);
  }
  fprintf (stderr, "Claimed interface (ret: %d)\n", ret);

  ret = usb_set_altinterface(devh, 0);
  assert(ret >= 0);

  ret = usb_get_descriptor(devh, 0x0000001, 0x0000000, buf, 0x0000012);
  ret = usb_get_descriptor(devh, 0x0000002, 0x0000000, buf, 0x0000009);
  ret = usb_get_descriptor(devh, 0x0000002, 0x0000000, buf, 0x0000022);
  usleep(1*1000);
  ret = usb_release_interface(devh, 0);
  if (ret != 0) fprintf (stderr, "failed to release interface before set_configuration: %d\n", ret);
  ret = usb_set_configuration(devh, 0x0000001);
  ret = usb_claim_interface(devh, 0);
  if (ret != 0) fprintf (stderr, "claim after set_configuration failed with error %d\n", ret);
  ret = usb_set_altinterface(devh, 0);
  usleep(35*1000);
  ret = usb_control_msg(devh, USB_TYPE_CLASS + USB_RECIP_INTERFACE, 0x000000a, 0x0000000, 0x0000000, buf, 0x0000000, 1000);
  usleep(1*1000);
  ret = usb_get_descriptor(devh, 0x0000022, 0x0000000, buf, 0x0000062);
  usleep(5*1000);
  ret = usb_interrupt_read(devh, 0x00000081, buf, 0x0000008, 1000);

  fprintf (stderr, "Type, bytes: ");
  print_bytes(buf, ret);
  fprintf (stderr, "\n");
  ret = usb_interrupt_read(devh, 0x00000081, buf, 0x0000008, 1000);
  if ( ret == 8) {
    fprintf (stderr, "Type, bytes: ");
    print_bytes(buf, ret);
  }
  fprintf (stderr, "\n");
  usleep(2500*1000);

  /* Class Interface 20 00 08 01 00 00 00 00 */
  memcpy(buf, "\x20\x00\x08\x01\x00\x00\x00\x00", 0x0000008);
  ret = usb_control_msg(devh, USB_TYPE_CLASS + USB_RECIP_INTERFACE, 0x0000009, 0x0000200, 0x0000000, buf, 0x0000008, 1000);
  usleep(100*1000);

  fprintf (stderr, "Forking to background...\n");

  if ((pid = fork ()))
  {
    if (pid == -1)
      fprintf (stderr, "error forking!\n");
    else
      fprintf (stderr, "continuing as pid %d\n", pid);

    return 0;
  }

  while (1)
  {
    int j = 0;
    int read = 0;
    FILE *bin;

    /* Class Interface 01 d0 08 01 00 00 00 00 */
    memcpy(buf, "\x01\xd0\x08\x01\x00\x00\x00\x00", 0x0000008);
    ret = usb_control_msg(devh, USB_TYPE_CLASS + USB_RECIP_INTERFACE, 0x0000009, 0x0000200, 0x0000000, buf, 0x0000008, 1000);
    usleep(100*1000);

    data_pos = 0;
    do {
      usleep(100*1000);
      ret = usb_interrupt_read(devh, 0x00000081, buf, 0x0000008, 1000);
      if( ret == 8) {
        memcpy(buf2+(j*8), buf, 8);

        memcpy (data + data_pos, buf + 1, (int )buf[0]);
        data_pos += (int) buf[0];
      } 
      else if (ret < 0)
      {
        break;
      }

      read += ret;
    } while (read < 1024); 

    if (data_pos <= 0)
      continue;

    bin = fopen ("weather-log.bin", "a");
    fwrite (data, sizeof (char), data_pos, bin);
    fclose (bin);
  }


  ret = usb_release_interface(devh, 0);
  assert(ret == 0);

  ret = usb_close(devh);
  assert(ret == 0);

  return 0;
}
